### ISSUE TITLE
I try to do what the post says and it doesn't work. I cannot have a DateTimePicker with no value. I also have no way to tell if this is an old feature that was removed or a new feature that I need to upgrade to get working.

### ISSUE THREAD

**Issue by McCoyITDept** [telerik/winforms-docs#47]

**Comment by McCoyITDept** [comment]
I try to do what the post says and it doesn't work. I cannot have a DateTimePicker with no value. I also have no way to tell if this is an old feature that was removed or a new feature that I need to upgrade to get working

The version I have uses CHECKED to indicate if there is a value but that appears to do nothing while it does not HAVE the SETTONULLVALUE feature.

**Comment by DKaramfilov** [comment]
Hi, 
I have checked this and this functionality is available since 2010. I am not sure why it is not working on your side. However, this is not the proper place to discuss that and I want to kindly ask you to post in our [forum](https://www.telerik.com/forums/winforms) or submit a new support ticket for this. 

Thank you for your understanding.

Regards,
Dimitar
